# Prerequisites

Welcome to R for Loss Data Analytics. This site provides files that generate R codes to support the online text Loss Data Analytics. Within the site, there are explanations available to guide you through the specific R functions used in a certain code chunk so that you can understand what the code is doing and why we need to use such a function. In order to use this site most effectively, it is helpful to learn and understand the following programming tools in R. By having this background knowledge, you can manipulate the given code to suit your application. 

Useful programming tools you should know: 

1. Install and call packages within RStudio
2. Assign values to variables
3. Construct and select particular elements of
    + Vectors
    + Matrices
    + Data frames  
4. Construct plots
    + Histograms
    + Lines
    + Curves
    + Multiple plots in one output
    + Include labels, x and y limits, color and a legend  
5. Construct and call functions
6. Construct loops
7. Construct if else statements
8. Read and manipulate data
    + Read in files
    + Take a subset of the data
    + Get certain elements of the data
    
The following are free sections within DataCamp courses that can help you understand these programming tools.

* **Working with the RStudio IDE (Part 1)** - Orientation (for 1)
* **Introduction to R** - Intro to basics, Vectors, Matrices, Data frames (for 2 and 3)
* **Data Visualization in R** - A quick introduction to base R graphics (for 4)
* **Writing Functions in R** - A quick refresher (for 5 and 6)
* **Intermediate R** - Conditionals and Control Flow (for 7)
* **Importing & Cleaning Data in R** - Ticket Sales Data (for 8)

Further, we suggest using RMarkdown when writing a report. This package allows you to record both your code and output in a single file.
