# Prerequisites {-}

Welcome to R for Loss Data Analytics. This site provides files that generate R codes to support the online text Loss Data Analytics. Within the site, there are explanations available to guide you through the specific R functions used in a certain code chunk so that you can understand what the code is doing and why we need to use such a function. In order to use this site most effectively, it is helpful to learn and understand the following programming tools in R. By having this background knowledge, you can manipulate the given code to suit your application. 

## Basic Programming Tools
These are tools that *you should know* as you use this site. **Introduction to R** is a free course available on [DataCamp](https://www.datacamp.com/) that can help you understand them in detail.

* Assign values to variables
* Construct and select particular elements of
    + Vectors
    + Matrices
    + Data frames

## Further Programming Tools
These are tools that are *helpful to know*. These are tools used throughout the site, though we deem them as optional to know since it is not required to understand the code provided.

* Install and call packages within RStudio
* Construct plots
    + Histograms
    + Lines
    + Curves
    + Multiple plots in one output
    + Include labels, x and y limits, color and a legend  
* Construct and call functions
* Construct loops
* Construct if else statements
* Read and manipulate data
    + Read in files
    + Take a subset of the data
    + Get certain elements of the data
    
## R Markdown
We suggest using R Markdown when *writing a report*. R Markdown is a package available in RStudio that allows you to record both your code and output in a single file. You can refer [here](https://rmarkdown.rstudio.com/index.html) to learn more about this package.
